#include <stm32f30x.h>
int main()
{RCC->AHBENR |= RCC_AHBENR_GPIOEEN;//ABILITATO IL CLOCK ALLA PERIFERICA
GPIOE->MODER |= GPIO_MODER_MODER8_0;//SETTO GPIOE LINEA 8 COME USCITA DIGITALE
                                    //PE8 E' LEGATO AL LED4
GPIOE->ODR |= GPIO_ODR_8;
while(1);
}