#include <stm32f30x.h>
unsigned int i=0;
int main()
{RCC->AHBENR |= RCC_AHBENR_GPIOEEN;
RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
GPIOE->MODER |=GPIO_MODER_MODER8_0|GPIO_MODER_MODER9_0|GPIO_MODER_MODER10_0|GPIO_MODER_MODER11_0|GPIO_MODER_MODER12_0|GPIO_MODER_MODER13_0|GPIO_MODER_MODER14_0|GPIO_MODER_MODER15_0 ;
GPIOA->MODER &=0xFFFFFFFC;
while(1){
  if(GPIOA->IDR&GPIO_IDR_0==1){
while(GPIOA->IDR&GPIO_IDR_0==1);
i++;
GPIOE->ODR |= (i<<8);
}
}
}