#include <stm32f30x.h>
unsigned int i=0;
int main()
{RCC->AHBENR |= RCC_AHBENR_GPIOEEN;
GPIOE->MODER |=GPIO_MODER_MODER8_0|GPIO_MODER_MODER9_0|GPIO_MODER_MODER10_0|GPIO_MODER_MODER11_0|GPIO_MODER_MODER12_0|GPIO_MODER_MODER13_0|GPIO_MODER_MODER14_0|GPIO_MODER_MODER15_0 ;
RCC->APB1ENR |= RCC_APB1ENR_TIM7EN;
TIM7->ARR =10000;
TIM7->PSC =7199;
TIM7->CNT=0;
TIM7->DIER |=TIM_DIER_UIE;
NVIC->ISER[1] |=(1<<23);

TIM7->CR1 |=TIM_CR1_CEN;
while(1);
}

void TIM7_IRQHandler(){
    TIM7->SR &= ~TIM_SR_UIF;
    i++;
    GPIOE->ODR |= (i<<8);
}
