#include <stm32f30x.h>
#include <stdio.h>
int i=0;
int main()
{RCC->AHBENR |=RCC_AHBENR_GPIOEEN;
GPIOE->MODER |=GPIO_MODER_MODER8_0|GPIO_MODER_MODER9_0|GPIO_MODER_MODER10_0|GPIO_MODER_MODER11_0|GPIO_MODER_MODER12_0|GPIO_MODER_MODER13_0|GPIO_MODER_MODER14_0|GPIO_MODER_MODER15_0;
RCC->APB1ENR |=RCC_APB1ENR_TIM2EN;
TIM2->ARR =272808000;
TIM2->CNT=0;
TIM2->DIER |= TIM_DIER_UIE;
NVIC->ISER[0] |= (1<<28);
TIM2->CR1 |= TIM_CR1_CEN;
 while(1);
}

void  TIM2_IRQHandler(){
  printf("entra\n");
  TIM2->SR &= ~TIM_SR_UIF;
  i++;
GPIOE->ODR |= (i<<8);
}