#include <stm32f30x.h>
int main()
{RCC->AHBENR |= RCC_AHBENR_GPIOEEN;
RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
GPIOE->MODER |=GPIO_MODER_MODER8_0|GPIO_MODER_MODER9_0|GPIO_MODER_MODER10_0|GPIO_MODER_MODER11_0|GPIO_MODER_MODER12_0|GPIO_MODER_MODER13_0|GPIO_MODER_MODER14_0|GPIO_MODER_MODER15_0 ;
GPIOA->MODER &=0xFFFFFFFC;
while(1){
while(GPIOA->IDR&GPIO_IDR_0==1){
GPIOE->ODR |= GPIO_ODR_8 | GPIO_ODR_9| GPIO_ODR_10| GPIO_ODR_11| GPIO_ODR_12| GPIO_ODR_13| GPIO_ODR_14| GPIO_ODR_15;  
}

GPIOE->ODR &= ~GPIO_ODR_8;
GPIOE->ODR &= ~GPIO_ODR_9;
GPIOE->ODR &= ~GPIO_ODR_10;
GPIOE->ODR &= ~GPIO_ODR_11;
GPIOE->ODR &= ~GPIO_ODR_12;
GPIOE->ODR &= ~GPIO_ODR_13;
GPIOE->ODR &= ~GPIO_ODR_14;
GPIOE->ODR &= ~GPIO_ODR_15;
}
}