#include <stm32f30x.h>
unsigned int i=0;
int main()
{RCC->AHBENR |= RCC_AHBENR_GPIOEEN;
GPIOE->MODER |=GPIO_MODER_MODER8_0|GPIO_MODER_MODER9_0|GPIO_MODER_MODER10_0|GPIO_MODER_MODER11_0|GPIO_MODER_MODER12_0|GPIO_MODER_MODER13_0|GPIO_MODER_MODER14_0|GPIO_MODER_MODER15_0 ;
RCC->APB1ENR |= RCC_APB1ENR_TIM6EN;
TIM6->ARR =1000;
TIM6->PSC =7999;
TIM6->CR1 |=TIM_CR1_CEN;
while(1){
  if((TIM6->SR & TIM_SR_UIF)== TIM_SR_UIF){
    TIM6->SR &= ~TIM_SR_UIF;
i++;
GPIOE->ODR |= (i<<8);
  }
}
}