#include <stm32f30x.h>
int cont=0;
int main()
{RCC->AHBENR |=RCC_AHBENR_GPIOEEN;
RCC->AHBENR |=RCC_AHBENR_GPIOAEN;
GPIOA->MODER &= ~GPIO_MODER_MODER0;
GPIOE->MODER |=GPIO_MODER_MODER8_0|GPIO_MODER_MODER9_0|GPIO_MODER_MODER10_0|GPIO_MODER_MODER11_0|GPIO_MODER_MODER12_0|GPIO_MODER_MODER13_0|GPIO_MODER_MODER14_0|GPIO_MODER_MODER15_0;
RCC->APB1ENR |=RCC_APB1ENR_TIM2EN;
TIM2->ARR =272808000;
TIM2->DIER |=TIM_DIER_UIE;
NVIC->ISER[0] |= (1<<28);
EXTI->IMR |=EXTI_IMR_MR0;
EXTI->RTSR |=EXTI_RTSR_TR0;
NVIC->ISER[0] |= (1<<6);
TIM2->CR1 |=TIM_CR1_CEN;
  while(1);
}
void EXTI0_IRQHandler(){
EXTI->PR |=EXTI_PR_PR0;
TIM2->CR1 &= ~TIM_CR1_CEN;
TIM2->CNT =0;

cont=0;
GPIOE->ODR &= ~GPIO_ODR_8;
GPIOE->ODR &= ~GPIO_ODR_9;
GPIOE->ODR &= ~GPIO_ODR_10;
GPIOE->ODR &= ~GPIO_ODR_11;
GPIOE->ODR &= ~GPIO_ODR_12;
GPIOE->ODR &= ~GPIO_ODR_13;
GPIOE->ODR &= ~GPIO_ODR_14;
GPIOE->ODR &= ~GPIO_ODR_15;
TIM2->CR1 |=TIM_CR1_CEN;
}
void TIM2_IRQHandler(){
TIM2->SR &= ~TIM_SR_UIF;
cont++;
GPIOE->ODR |=(cont<<8);
}